package br.com.controlpass.model;
// Generated 24/04/2018 21:53:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblMateria generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private int idMateria;
     private String nmMateria;
     private Set chamadas = new HashSet(0);



	
    public Materia(int idMateria, String nmMateria) {
        this.idMateria = idMateria;
        this.nmMateria = nmMateria;
    }
    public Materia(int idMateria, String nmMateria, Set chamadas) {
       this.idMateria = idMateria;
       this.nmMateria = nmMateria;
       this.chamadas = chamadas;
    }
   
    public int getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(int idMateria) {
        this.idMateria = idMateria;
    }
    public String getNmMateria() {
        return this.nmMateria;
    }
    
    public void setNmMateria(String nmMateria) {
        this.nmMateria = nmMateria;
    }
    public Set getChamadas() {
        return this.chamadas;
    }
    
    public void setChamadas(Set chamadas) {
        this.chamadas = chamadas;
    }




}


