package br.com.controlpass.model;
// Generated 24/04/2018 21:53:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblAluno generated by hbm2java
 */
public class TblAluno  implements java.io.Serializable {


     private int idAluno;
     private TblUsuario tblUsuario;
     private int codigoBiometria;
     private Set tblChamadas = new HashSet(0);

    public TblAluno() {
    }

	
    public TblAluno(int idAluno, TblUsuario tblUsuario, int codigoBiometria) {
        this.idAluno = idAluno;
        this.tblUsuario = tblUsuario;
        this.codigoBiometria = codigoBiometria;
    }
    public TblAluno(int idAluno, TblUsuario tblUsuario, int codigoBiometria, Set tblChamadas) {
       this.idAluno = idAluno;
       this.tblUsuario = tblUsuario;
       this.codigoBiometria = codigoBiometria;
       this.tblChamadas = tblChamadas;
    }
   
    public int getIdAluno() {
        return this.idAluno;
    }
    
    public void setIdAluno(int idAluno) {
        this.idAluno = idAluno;
    }
    public TblUsuario getTblUsuario() {
        return this.tblUsuario;
    }
    
    public void setTblUsuario(TblUsuario tblUsuario) {
        this.tblUsuario = tblUsuario;
    }
    public int getCodigoBiometria() {
        return this.codigoBiometria;
    }
    
    public void setCodigoBiometria(int codigoBiometria) {
        this.codigoBiometria = codigoBiometria;
    }
    public Set getTblChamadas() {
        return this.tblChamadas;
    }
    
    public void setTblChamadas(Set tblChamadas) {
        this.tblChamadas = tblChamadas;
    }




}


