package br.com.controlpass.model;
// Generated 24/04/2018 21:53:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblCurso generated by hbm2java
 */
public class TblCurso  implements java.io.Serializable {


     private int idCurso;
     private int qtdModulo;
     private Set tblChamadas = new HashSet(0);
     private Set tblTurmas = new HashSet(0);

    public TblCurso() {
    }

	
    public TblCurso(int idCurso, int qtdModulo) {
        this.idCurso = idCurso;
        this.qtdModulo = qtdModulo;
    }
    public TblCurso(int idCurso, int qtdModulo, Set tblChamadas, Set tblTurmas) {
       this.idCurso = idCurso;
       this.qtdModulo = qtdModulo;
       this.tblChamadas = tblChamadas;
       this.tblTurmas = tblTurmas;
    }
   
    public int getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }
    public int getQtdModulo() {
        return this.qtdModulo;
    }
    
    public void setQtdModulo(int qtdModulo) {
        this.qtdModulo = qtdModulo;
    }
    public Set getTblChamadas() {
        return this.tblChamadas;
    }
    
    public void setTblChamadas(Set tblChamadas) {
        this.tblChamadas = tblChamadas;
    }
    public Set getTblTurmas() {
        return this.tblTurmas;
    }
    
    public void setTblTurmas(Set tblTurmas) {
        this.tblTurmas = tblTurmas;
    }




}


