package br.com.controlpass.model;
// Generated 24/04/2018 21:53:31 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblChamada generated by hbm2java
 */
public class TblChamada  implements java.io.Serializable {


     private int idChamada;
     private TblAluno tblAluno;
     private TblCurso tblCurso;
     private TblMateria tblMateria;
     private TblTurma tblTurma;
     private Date data;
     private Date horaInicio;
     private Date horaFinal;

    public TblChamada() {
    }

    public TblChamada(int idChamada, TblAluno tblAluno, TblCurso tblCurso, TblMateria tblMateria, TblTurma tblTurma, Date data, Date horaInicio, Date horaFinal) {
       this.idChamada = idChamada;
       this.tblAluno = tblAluno;
       this.tblCurso = tblCurso;
       this.tblMateria = tblMateria;
       this.tblTurma = tblTurma;
       this.data = data;
       this.horaInicio = horaInicio;
       this.horaFinal = horaFinal;
    }
   
    public int getIdChamada() {
        return this.idChamada;
    }
    
    public void setIdChamada(int idChamada) {
        this.idChamada = idChamada;
    }
    public TblAluno getTblAluno() {
        return this.tblAluno;
    }
    
    public void setTblAluno(TblAluno tblAluno) {
        this.tblAluno = tblAluno;
    }
    public TblCurso getTblCurso() {
        return this.tblCurso;
    }
    
    public void setTblCurso(TblCurso tblCurso) {
        this.tblCurso = tblCurso;
    }
    public TblMateria getTblMateria() {
        return this.tblMateria;
    }
    
    public void setTblMateria(TblMateria tblMateria) {
        this.tblMateria = tblMateria;
    }
    public TblTurma getTblTurma() {
        return this.tblTurma;
    }
    
    public void setTblTurma(TblTurma tblTurma) {
        this.tblTurma = tblTurma;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFinal() {
        return this.horaFinal;
    }
    
    public void setHoraFinal(Date horaFinal) {
        this.horaFinal = horaFinal;
    }




}


