package br.com.controlpass.model;
// Generated 24/04/2018 21:53:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblTurma generated by hbm2java
 */
public class TblTurma  implements java.io.Serializable {


     private int idTurma;
     private TblCurso tblCurso;
     private String nmTurma;
     private Set tblChamadas = new HashSet(0);

    public TblTurma() {
    }

	
    public TblTurma(int idTurma, TblCurso tblCurso, String nmTurma) {
        this.idTurma = idTurma;
        this.tblCurso = tblCurso;
        this.nmTurma = nmTurma;
    }
    public TblTurma(int idTurma, TblCurso tblCurso, String nmTurma, Set tblChamadas) {
       this.idTurma = idTurma;
       this.tblCurso = tblCurso;
       this.nmTurma = nmTurma;
       this.tblChamadas = tblChamadas;
    }
   
    public int getIdTurma() {
        return this.idTurma;
    }
    
    public void setIdTurma(int idTurma) {
        this.idTurma = idTurma;
    }
    public TblCurso getTblCurso() {
        return this.tblCurso;
    }
    
    public void setTblCurso(TblCurso tblCurso) {
        this.tblCurso = tblCurso;
    }
    public String getNmTurma() {
        return this.nmTurma;
    }
    
    public void setNmTurma(String nmTurma) {
        this.nmTurma = nmTurma;
    }
    public Set getTblChamadas() {
        return this.tblChamadas;
    }
    
    public void setTblChamadas(Set tblChamadas) {
        this.tblChamadas = tblChamadas;
    }




}


