package br.com.controlpass.model;
// Generated 24/04/2018 21:53:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblTurma generated by hbm2java
 */
public class Turma  implements java.io.Serializable {


     private int idTurma;
     private Curso curso;
     private String nmTurma;
     private Set chamadas = new HashSet(0);

 

	
    public Turma(int idTurma, Curso curso, String nmTurma) {
        this.idTurma = idTurma;
        this.curso = curso;
        this.nmTurma = nmTurma;
    }
    public Turma(int idTurma, Curso curso, String nmTurma, Set tblChamadas) {
       this.idTurma = idTurma;
       this.curso = curso;
       this.nmTurma = nmTurma;
       this.chamadas = chamadas;
    }
   
    public int getIdTurma() {
        return this.idTurma;
    }
    
    public void setIdTurma(int idTurma) {
        this.idTurma = idTurma;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
   
    public String getNmTurma() {
        return this.nmTurma;
    }
    
    public void setNmTurma(String nmTurma) {
        this.nmTurma = nmTurma;
    }

    public Set getChamadas() {
        return chamadas;
    }

    public void setChamadas(Set chamadas) {
        this.chamadas = chamadas;
    }
    




}


