package br.com.controlpass.model;
// Generated 24/04/2018 21:53:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblUsuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private int cpf;
     private String nome;
     private int tipoUsuario;
     private String email;
     private int status;
     private String login;
     private String senha;
     private Set alunos = new HashSet(0);



	
    public Usuario(int idUsuario, int cpf, String nome, int tipoUsuario, String email, int status, String login, String senha) {
        this.idUsuario = idUsuario;
        this.cpf = cpf;
        this.nome = nome;
        this.tipoUsuario = tipoUsuario;
        this.email = email;
        this.status = status;
        this.login = login;
        this.senha = senha;
    }
    public Usuario(int idUsuario, int cpf, String nome, int tipoUsuario, String email, int status, String login, String senha, Set tblAlunos) {
       this.idUsuario = idUsuario;
       this.cpf = cpf;
       this.nome = nome;
       this.tipoUsuario = tipoUsuario;
       this.email = email;
       this.status = status;
       this.login = login;
       this.senha = senha;
       this.alunos = tblAlunos;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getCpf() {
        return this.cpf;
    }
    
    public void setCpf(int cpf) {
        this.cpf = cpf;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public int getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(int tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set getalunos() {
        return this.alunos;
    }
    
    public void setTblAlunos(Set alunos) {
        this.alunos = alunos;
    }




}


